# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-pat

name: generate HTML report

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
       
       
           
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
           java-version: '11'
           distribution: 'adopt'
           cache: maven
        - name: Build with Maven
          run: mvn -B package --file pom.xml
       

        - name: Deploy report page to Github page
          uses: peaceiris/actions-gh-pages@v3
          with:
            deploy_key: ${{secrets.DEPLOY_PRIVATE_KEY}} 
            publish_branch: gh-pages
            publish_dir: ./target/surefire-reports/testng_metrics.html
            
          
          
