# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-pat

name: generate HTML report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  cypress-test:
    name: Run on chrome 94
    runs-on: ubuntu-18.04
    container: cypress/browsers:node16.5.0-chrome94-ff93  
      
   
    steps:
        - uses: actions/checkout@v2
       
        - name: Run cypress tests
          run: npm run test:chrome
           continue-on-error:false
           
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
           java-version: '11'
           distribution: 'adopt'
           cache: maven
        - name: Build with Maven
          run: mvn -B package --file pom.xml
       
        - name: Merge test reports
          run: npm run combine :report
        - name: Generate HTML report
          run: npm run generate :report
        - name: Deploy report page to Github page
          uses: peaceiris/actions-gh-pages@v3
          with:
            github-token: ${{secrets.GITHUB-TOKEN}}
            publish-dir: ./public
          
          
